name: Generate CHANGELOG

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      # Récupère le contenu de la branche de la Release.
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      # Configure Node.js et intie le cache.
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
          cache: npm

      # Installe les dépendances
      - name: Install dependencies
        run: npm ci

      # Génère et enregistre la liste de commits.
      - name: Generate commits list
        env: 
          CURRENT_TAG: ${{ github.event.release.tag_name }}
        run: node scripts/changelog-generator/generate-commits-list.mjs

      # Génère le contenu de la release et l'enregistre dans le CHANGELOG.md.
      - name: Generate Release content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
        run: node scripts/changelog-generator/generate-changelog.mjs

      # Ajoute le contenu généré au notes de Release.
      - name: Update Git Release notes
        env:
          GH_TOKEN: ${{ github.token }}
          CURRENT_TAG: ${{ github.event.release.tag_name }}
        run: |
          gh release edit "$CURRENT_TAG" \
            --notes-file scripts/changelog-generator/release-notes.md

      # Vérifie si des changements ont eu lieu dand le CHANGELOG.md.
      - name: Check changes
        id: changes
        run: |
          if git diff --quiet -- CHANGELOG.md; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      # Configure l'utilisateur Git pour le commit automatique.
      - name: Configure Git
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Créer un commit uniquement pour le CHANGELOG.md.
      - name: Commit CHANGELOG
        if: steps.changes.outputs.changed == 'true'
        run: |
          git add CHANGELOG.md
          git commit -m "docs(changelog): update/generate release ${{ github.event.release.target_commitish }}"
          
      #  Push le commit sur la branche de la Release.
      - name: Push CHANGELOG
        if: steps.changes.outputs.changed == 'true'
        run: |
          git push origin HEAD:${{ github.event.release.target_commitish }}