name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  generate-changelog:
    uses: ./.github/workflows/release-generate-changelog.yml
    with:
      tag_name: ${{ github.event.release.tag_name }}
      target_commitish: ${{ github.event.release.target_commitish }}
      bp_openai_model: ${{ vars.BP_OPENAI_MODEL }}
    secrets:
      bp_openai_api_key: ${{ secrets.BP_OPENAI_API_KEY }}

  notify-release:
    needs: generate-changelog
    uses: ./.github/workflows/release-notify.yml
    secrets:
      bp_webhook_secret: ${{ secrets.BP_NOTIFICATIONS_GITHUB_RELEASES_WEBHOOK_SECRET }}
