name: Validate Renovate

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  check-results:
    if: startsWith(github.head_ref, 'renovate/')

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Notify backtik
        env:
          API_URL: https://notifications.backtik.ch/api/notifications/renovate
          REPOSITORY: ${{ github.repository }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl \
          --fail \
          --silent \
          --show-error \
          --request POST \
          --header "Content-Type: application/json" \
          --data "$(jq -n \
            --arg repository "$REPOSITORY" \
            --arg pull_request "$PR_TITLE" \
            --arg pull_request_url "$PR_URL" \
            '{
              repository: $repository,
              updates: [{
                pull_request: $pull_request,
                status: "ready",
                pull_request_url: $pull_request_url
              }]
            }'
          )" \
          "$API_URL"