name: Validate Renovate

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  check-tests:
    if: github.event.workflow_run.event == 'pull_request' && startsWith(github.event.workflow_run.head_branch, 'renovate/')
    
    runs-on: ubuntu-latest

    steps:
      - name: Close PR (if tests failed)
        if: github.event.workflow_run.conclusion != 'success'
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh pr close "$PR_NUMBER" \
            --repo "$REPOSITORY" \
            --comment "Une suite de tests ou plus a échoué…" \
            --delete-branch
      
      - name: Notify backtik
        if: github.event.workflow_run.conclusion == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
          API_URL: https://notifications.backtik.ch/api/notifications/renovate
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          PR_TITLE=$(gh pr view "$PR_NUMBER" --repo "$REPOSITORY" --json title -q .title)
          PR_URL=$(gh pr view "$PR_NUMBER" --repo "$REPOSITORY" --json url -q .url)

          curl \
          --fail \
          --silent \
          --show-error \
          --request POST \
          --header "Content-Type: application/json" \
          --data "$(jq -n \
            --arg repository "$REPOSITORY" \
            --arg pull_request "$PR_TITLE" \
            --arg pull_request_url "$PR_URL" \
            '{
              repository: $repository,
              updates: [{
                pull_request: $pull_request,
                status: "ready",
                pull_request_url: $pull_request_url
              }]
            }'
          )" \
          "$API_URL"